### ISSUE TITLE
gamepad and keyboard app on the same smartphone?

### ISSUE THREAD

**Issue by Zack7765** [AppGround-io/bluetooth-gamepad-support#4]
Can both the gamepad and keyboard app be used on the same smartphone?
I have paired the keyboard app and can't additionally pair or connect the gamepad app.

**Comment by Zack7765** [comment]
In case that would be important as well.

Tested smartphones are the Galaxy S10 and S9.
The operating system of the paired PC is Windows 10.

**Comment by AppGround-io** [comment]
This is currently not possible, since the Bluetooth connection can only have one configuration, either gamepad or keyboard and mouse. It would theoretically be possible to create a single configuration with both, but this may not be supported by all systems.
 
This something to test, but for now only one configuration is supported.
